### ISSUE TITLE
Error - MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by sandyrs9421** [pashpashpash/vault-ai#47]
When i run command npm run dev i am getting below error.

FBT@pcadmins-MacBook-Pro vault-ai % sudo npm run dev              

> vault-web-server@1.0.0 dev
> webpack --progress --watch

[webpack-cli] Failed to load '/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'os-browserify/browser'
Require stack:
- /Users/FBT/Desktop/Projects/Chatdoc/vault-ai/webpack.config.js
- /Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack-cli/lib/bootstrap.js
- /Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack-cli/bin/cli.js
- /Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at Object.<anonymous> (/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/webpack.config.js:101:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at WebpackCLI.tryRequireThenImport (/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack-cli/lib/webpack-cli.js:216:22) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/webpack.config.js',
    '/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack-cli/bin/cli.js',
    '/Users/FBT/Desktop/Projects/Chatdoc/vault-ai/node_modules/webpack/bin/webpack.js'
  ]
}

can anyone please suggest on how to resolve this error ?

**Comment by sandyrs9421** [comment]
got the solution  for it
looks like it was issue with node version .
i ran below command and installed with correct version.

Post which it is working as expected.

Command - sudo rm -rf node_modules && npm install miller-rabin@1.1.1 --save-peer && npm install
